### Ссылки

* Семинары бакалаврского курс вшэ по эконометрике, [em301](http://bdemeshev.github.io/em301/)
* [Цикл заметок по R](http://bdemeshev.github.io/r_cycle/)
* [github-репозиторий](https://github.com/bdemeshev/em601) all files are available here even if there are no links below :)

###  Materials 2018-2019

A. Install R + Rstudio. [Installation instructions](https://bdemeshev.github.io/installation/r/R_installation.html).

* [Seminar 1. Probabilities for normal distribution, CI for mean](https://github.com/bdemeshev/em601/raw/master/2018/script_01_normal_sim_mean_ci.R )
* [Seminar 2. R + markdown report.](https://github.com/bdemeshev/em601/raw/master/2018/report.Rmd)
* [Seminar 3. R + markdown report. Flats dataset.](https://github.com/bdemeshev/em601/raw/master/2018/report_2.Rmd)
* [Final exam](https://github.com/bdemeshev/em601/raw/master/2018/final_2018_19/final_2018_19.pdf)

###  Materials 2017-2018

* [Script from 2017-11-22](https://github.com/bdemeshev/em601/raw/master/2017/seminar_2017_11_22.R)
* [Script from 2017-12-06](https://github.com/bdemeshev/em601/raw/master/2017/seminar_2017_12_06.R)
* [Script from 2018-01-10](https://github.com/bdemeshev/em601/raw/master/2017/seminar_2018_01_10.R)
* [Script from 2017-01-20](https://github.com/bdemeshev/em601/raw/master/2017/seminar_2018_01_20/report_demo.Rmd)
* [Script from 2018-02-16](https://github.com/bdemeshev/em601/raw/master/2017/seminar_2018_02_16.R)
* [Script from 2018-03-03](https://github.com/bdemeshev/em601/raw/master/2017/seminar_2018_03_03.R)
* [Script from 2018-03-14](https://github.com/bdemeshev/em601/raw/master/2017/seminar_2018_03_14.R)

* [Final exam](https://github.com/bdemeshev/em601/raw/master/2017/final_2017_18/final_2017_18.pdf)


###  Материалы 2016-2017

* [Семинар 1](https://github.com/bdemeshev/em601/raw/master/2016/sem_01.R). Введение в R. Множественная регрессия.
* [Семинар 2](https://github.com/bdemeshev/em601/raw/master/2016/sem_hetero.R). Гетероскедастичность, робастные стандартные ошибки.
* [Семинар 3](https://github.com/bdemeshev/em601/raw/master/2016/sem_hetero2.R). Гетероскедастичность, тесты. LASSO.

* [Экзамен](https://github.com/bdemeshev/em601/raw/master/2016/exam/binst_metrics_16.pdf)


###  Материалы 2015-2016

* [Экзамен](https://github.com/bdemeshev/em601/raw/master/2015/exam/binst_metrics_15.pdf)

* [Семинар 7](https://github.com/bdemeshev/em601/raw/master/2015/sem_07_panel.R): панельные данные

* [Семинар 6](https://github.com/bdemeshev/em601/raw/master/2015/sem_06x_iv.R): инструментальные переменные

* [Семинар 5](https://github.com/bdemeshev/em601/raw/master/2015/sem_06_hetero.R): гетероскедастичность

* [Семинар 4](https://github.com/bdemeshev/em601/raw/master/2015/sem_04_chow_test.R): дамми-переменные, тест Чоу
* [Семинар 3](https://github.com/bdemeshev/em601/raw/master/2015/sem_03.R): интервалы для прогнозов и сравнение вложенных моделей
* [Семинар 2](https://github.com/bdemeshev/em601/raw/master/2015/sem_02.R): проверка гипотез об отдельных коэффициентах
* [Семинар 1](https://github.com/bdemeshev/em601/raw/master/2015/sem_01.R): введение в R

###  Материалы 2014-2015

* [Экзамен](https://github.com/bdemeshev/em601/raw/master/2014/binst_exam/binst_metrics_14.pdf)
* [Домашка rlms](https://github.com/bdemeshev/em601/raw/master/2014/binst_ht_rlms/binst_ht_rlms.pdf)
* [Семинар 4](https://github.com/bdemeshev/em601/raw/master/2014/binst_sem_04.R)
* [Семинар 3](https://github.com/bdemeshev/em601/raw/master/2014/binst_sem_03.R)
* [Семинар 2](https://github.com/bdemeshev/em601/raw/master/2014/binst_sem_02.R)
* [Семинар 1](https://github.com/bdemeshev/em601/raw/master/2014/binst_sem_01/binst_sem_01.R)

###  Материалы 2013-2014

* [Экзамен](https://github.com/bdemeshev/em601/raw/master/2013/binst_metrix_exam_14/binst_metr_exam_14.pdf)
* [Семинар по гетероскедастичности](https://github.com/bdemeshev/em601/raw/master/2013/binst_hetero.R)
* [Семинар по ML](https://github.com/bdemeshev/em601/raw/master/2013/binst_ml_one.R)
* [Семинра по панельным данным](https://github.com/bdemeshev/em601/raw/master/2013/binst_panel.R)
* [Семинар по логит](https://github.com/bdemeshev/em601/raw/master/2013/binst_logit.R)
